name: Backend Continuous Integration
#The pipeline should be executed automatically on pull_request The pipeline should also be able to be run manually 
#The pipeline should be running without errors with all tests passing and no output failures from any of the steps
on:
  pull_request:
  #master is the main branch
    branches: [master]
    paths:
      - 'starter/backend/**'
  workflow_dispatch:
#The job and lint should complete before proceeding to the build step 
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: pip install
        run: |
          python -m pip install --upgrade pip
          pip install uwsgi
          pip install flask-cors
          pip install pytest
          pip install flask
          pip install Flake8
      - name: Linter
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v4
      - name: Use Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uwsgi
          pip install flask-cors
          pip install pytest
          pip install flask
      - name: Run tests
        run: |
          pytest .
#There should be a job that builds the application using docker.
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build -t backend-app .
