name: Backend Continuous Deployment

on:
  push:
  #master is the main branch
    branches: [master]
    paths: 
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
# There should be a step in the workflow that runs linting. 
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v4
      - name: Use Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uwsgi
          pip install flask-cors
          pip install pytest
          pip install flask
          pip install Flake8
      - name: Linter
        run: flake8 .
#There should be a step in the workflow that runs the tests
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v4
      - name: Use Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Pip Install
        run: |
          python -m pip install --upgrade pip
          pip install uwsgi
          pip install flask-cors
          pip install pytest
          pip install flask
      - name: Run tests
        run: |
          pytest .
#There should be a step that builds the application using docker.
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    environment: udacity
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v4
      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
#There should be a step that utilizes aws-actions/amazon-ecr-login action for logging into ECR. (using 3rd party actions) 
#The ECR login step should also be accessing Github Secrets for credentials. (secure approach)
      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Build 
        run: docker build -t backend .

      - name: Tag
        run: docker tag backend:latest ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA::7}
#There should be a step that pushes the docker image to ECR in the AWS account. 
      - name: Push
        run: docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA::7}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: udacity
    steps:
      - uses: actions/checkout@v4
      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Update Kuberntes config
        run: |
          aws eks update-kubeconfig --name cluster --region ${{ vars.AWS_DEFAULT_REGION }}
          kubectl config current-context
          kubectl get nodes
#There should be a step that deploys the application using kubectl to the Kubernetes cluster
      - name: Deploy
        id: deploy-k8s
        run: |
          kustomize edit set image backend=${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA::7}
          kustomize build | kubectl apply -f -
        working-directory: starter/backend/k8s
